"""add_user_api_key

Revision ID: b63a33f0daac
Revises: 5e8a1c2b3d4f
Create Date: 2026-07-07 12:40:15.064872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63a33f0daac'
down_revision: Union[str, Sequence[str], None] = '5e8a1c2b3d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 先添加为 nullable 列
    op.add_column('users', sa.Column('api_key', sa.String(length=64), nullable=True))
    # 2. 为现有行生成 api_key
    import uuid as _uuid
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id FROM users")).fetchall()
    for (user_id,) in users:
        connection.execute(
            sa.text("UPDATE users SET api_key = :key WHERE id = :id"),
            {"key": _uuid.uuid4().hex, "id": user_id}
        )
    # 3. 设置为 NOT NULL
    op.alter_column('users', 'api_key', nullable=False)
    # 4. 创建唯一索引
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
